#       define U_ICU_ENTRY_POINT_RENAME(x)    x

#define UCNV_FROM_U_CALLBACK_STOP U_ICU_ENTRY_POINT_RENAME(UCNV_FROM_U_CALLBACK_STOP)

void UCNV_FROM_U_CALLBACK_STOP(void);

void *f(void)
{
	return UCNV_FROM_U_CALLBACK_STOP;
}
