
// QtCore
//#include <QtCore/qabstractanimation.h>
//#include <QtCore/qabstracteventdispatcher.h>
#include <QtCore/qabstractitemmodel.h>
//#include <QtCore/qabstractnativeeventfilter.h>
#include <QtCore/qabstractproxymodel.h>
//#include <QtCore/qabstractstate.h>
//#include <QtCore/qabstracttransition.h>
#include <QtCore/qalgorithms.h>
//#include <QtCore/qanimationgroup.h>
#include <QtCore/qarraydata.h>
//#include <QtCore/qarraydataops.h>
//#include <QtCore/qarraydatapointer.h>
#include <QtCore/qatomic.h>
//#include <QtCore/qatomic_bootstrap.h>
#include <QtCore/qatomic_cxx11.h>
//#include <QtCore/qatomic_msvc.h>
#include <QtCore/qbasicatomic.h>
#include <QtCore/qbasictimer.h>
#include <QtCore/qbitarray.h>
//#include <QtCore/qbuffer.h>
#include <QtCore/qbytearray.h>
#include <QtCore/qbytearraylist.h>
//#include <QtCore/qbytearraymatcher.h>
//#include <QtCore/qcache.h>
#include <QtCore/qcalendar.h>
//#include <QtCore/qcborarray.h>
//#include <QtCore/qcborcommon.h>
//#include <QtCore/qcbormap.h>
//#include <QtCore/qcborstream.h>
//#include <QtCore/qcborstreamreader.h>
//#include <QtCore/qcborstreamwriter.h>
//#include <QtCore/qcborvalue.h>
#include <QtCore/qchar.h>
//#include <QtCore/qcollator.h>
//#include <QtCore/qcommandlineoption.h>
//#include <QtCore/qcommandlineparser.h>
#include <QtCore/qcompilerdetection.h>
#include <QtCore/qconcatenatetablesproxymodel.h>
#include <QtCore/qconfig.h>
//#include <QtCore/qconfig-bootstrapped.h>
#include <QtCore/qcontainerfwd.h>
#include <QtCore/qcontiguouscache.h>
#include <QtCore/qcoreapplication.h>
#include <QtCore/qcoreevent.h>
//#include <QtCore/qcryptographichash.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qdatetime.h>
//#include <QtCore/qdeadlinetimer.h>
#include <QtCore/qdebug.h>
#include <QtCore/qdir.h>
//#include <QtCore/qdiriterator.h>
#include <QtCore/qeasingcurve.h>
//#include <QtCore/qelapsedtimer.h>
//#include <QtCore/qendian.h>
#include <QtCore/qeventloop.h>
//#include <QtCore/qeventtransition.h>
//#include <QtCore/qexception.h>
//#include <QtCore/qfactoryinterface.h>
#include <QtCore/qfile.h>
#include <QtCore/qfiledevice.h>
#include <QtCore/qfileinfo.h>
//#include <QtCore/qfileselector.h>
//#include <QtCore/qfilesystemwatcher.h>
//#include <QtCore/qfinalstate.h>
#include <QtCore/qflags.h>
#include <QtCore/qfloat16.h>
//#include <QtCore/qfunctions_nacl.h>
//#include <QtCore/qfunctions_vxworks.h>
//#include <QtCore/qfunctions_winrt.h>
//#include <QtCore/qfuture.h>
//#include <QtCore/qfutureinterface.h>
//#include <QtCore/qfuturesynchronizer.h>
//#include <QtCore/qfuturewatcher.h>
#include <QtCore/qgenericatomic.h>
#include <QtCore/qglobal.h>
#include <QtCore/qglobalstatic.h>
#include <QtCore/qhash.h>
#include <QtCore/qhashfunctions.h>
//#include <QtCore/qhistorystate.h>
#include <QtCore/qidentityproxymodel.h>
#include <QtCore/qiodevice.h>
//#include <QtCore/qisenum.h>
#include <QtCore/qitemselectionmodel.h>
#include <QtCore/qiterator.h>
//#include <QtCore/qjsonarray.h>
//#include <QtCore/qjsondocument.h>
//#include <QtCore/qjsonobject.h>
//#include <QtCore/qjsonvalue.h>
//#include <QtCore/qlibrary.h>
//#include <QtCore/qlibraryinfo.h>
#include <QtCore/qline.h>
//#include <QtCore/qlinkedlist.h>
#include <QtCore/qlist.h>
#include <QtCore/qlocale.h>
//#include <QtCore/qlockfile.h>
#include <QtCore/qlogging.h>
//#include <QtCore/qloggingcategory.h>
#include <QtCore/qmap.h>
#include <QtCore/qmargins.h>
//#include <QtCore/qmath.h>
//#include <QtCore/qmessageauthenticationcode.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qmetatype.h>
#include <QtCore/qmimedata.h>
//#include <QtCore/qmimedatabase.h>
//#include <QtCore/qmimetype.h>
#include <QtCore/qmutex.h>
#include <QtCore/qnamespace.h>
#include <QtCore/qnumeric.h>
#include <QtCore/qobject.h>
//#include <QtCore/qobjectcleanuphandler.h>
#include <QtCore/qobjectdefs.h>
//#include <QtCore/qoperatingsystemversion.h>
#include <QtCore/qpair.h>
//#include <QtCore/qparallelanimationgroup.h>
//#include <QtCore/qpauseanimation.h>
//#include <QtCore/qplugin.h>
//#include <QtCore/qpluginloader.h>
#include <QtCore/qpoint.h>
//#include <QtCore/qpointer.h>
//#include <QtCore/qprocess.h>
#include <QtCore/qprocessordetection.h>
//#include <QtCore/qpropertyanimation.h>
//#include <QtCore/qqueue.h>
//#include <QtCore/qrandom.h>
//#include <QtCore/qreadwritelock.h>
#include <QtCore/qrect.h>
#include <QtCore/qrefcount.h>
#include <QtCore/qregexp.h>
#include <QtCore/qregularexpression.h>
//#include <QtCore/qresource.h>
//#include <QtCore/qresultstore.h>
//#include <QtCore/qrunnable.h>
//#include <QtCore/qsavefile.h>
#include <QtCore/qscopedpointer.h>
//#include <QtCore/qscopedvaluerollback.h>
//#include <QtCore/qscopeguard.h>
//#include <QtCore/qsemaphore.h>
//#include <QtCore/qsequentialanimationgroup.h>
#include <QtCore/qset.h>
//#include <QtCore/qsettings.h>
#include <QtCore/qshareddata.h>
//#include <QtCore/qsharedmemory.h>
//#include <QtCore/qsharedpointer.h>
//#include <QtCore/qsignalmapper.h>
//#include <QtCore/qsignaltransition.h>
#include <QtCore/qsize.h>
//#include <QtCore/qsocketnotifier.h>
#include <QtCore/qsortfilterproxymodel.h>
//#include <QtCore/qstack.h>
#include <QtCore/qstandardpaths.h>
//#include <QtCore/qstate.h>
//#include <QtCore/qstatemachine.h>
//#include <QtCore/qstorageinfo.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringalgorithms.h>
#include <QtCore/qstringbuilder.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qstringlistmodel.h>
#include <QtCore/qstringliteral.h>
#include <QtCore/qstringmatcher.h>
#include <QtCore/qstringview.h>
#include <QtCore/qsysinfo.h>
//#include <QtCore/qsystemdetection.h>
//#include <QtCore/qsystemsemaphore.h>
//#include <QtCore/qtcoreversion.h>
//#include <QtCore/qtcore-config.h>
//#include <QtCore/qtemporarydir.h>
//#include <QtCore/qtemporaryfile.h>
//#include <QtCore/qtestsupport_core.h>
//#include <QtCore/qtextboundaryfinder.h>
#include <QtCore/qtextcodec.h>
#include <QtCore/qtextstream.h>
#include <QtCore/qthread.h>
//#include <QtCore/qthreadpool.h>
//#include <QtCore/qthreadstorage.h>
//#include <QtCore/qtimeline.h>
#include <QtCore/qtimer.h>
#include <QtCore/qtimezone.h>
//#include <QtCore/qtranslator.h>
#include <QtCore/qtransposeproxymodel.h>
#include <QtCore/qtypeinfo.h>
//#include <QtCore/qtypetraits.h>
//#include <QtCore/qt_windows.h>
#include <QtCore/qurl.h>
//#include <QtCore/qurlquery.h>
#include <QtCore/quuid.h>
#include <QtCore/qvariant.h>
//#include <QtCore/qvariantanimation.h>
#include <QtCore/qvarlengtharray.h>
#include <QtCore/qvector.h>
//#include <QtCore/qversionnumber.h>
#include <QtCore/qversiontagging.h>
//#include <QtCore/qwaitcondition.h>
//#include <QtCore/qwineventnotifier.h>
//#include <QtCore/qxmlstream.h>

// QtGui
#include <QtGui/qabstracttextdocumentlayout.h>
//#include <QtGui/qaccessible.h>
//#include <QtGui/qaccessiblebridge.h>
//#include <QtGui/qaccessibleobject.h>
//#include <QtGui/qaccessibleplugin.h>
//#include <QtGui/qbackingstore.h>
#include <QtGui/qbitmap.h>
#include <QtGui/qbrush.h>
#include <QtGui/qclipboard.h>
#include <QtGui/qcolor.h>
#include <QtGui/qcolorspace.h>
#include <QtGui/qcolortransform.h>
#include <QtGui/qcursor.h>
#include <QtGui/qdesktopservices.h>
#include <QtGui/qdrag.h>
#include <QtGui/qevent.h>
#include <QtGui/qfont.h>
#include <QtGui/qfontdatabase.h>
#include <QtGui/qfontinfo.h>
#include <QtGui/qfontmetrics.h>
//#include <QtGui/qgenericmatrix.h>
//#include <QtGui/qgenericplugin.h>
//#include <QtGui/qgenericpluginfactory.h>
#include <QtGui/qglyphrun.h>
#include <QtGui/qguiapplication.h>
#include <QtGui/qicon.h>
//#include <QtGui/qiconengine.h>
//#include <QtGui/qiconengineplugin.h>
#include <QtGui/qimage.h>
#include <QtGui/qimageiohandler.h>
#include <QtGui/qimagereader.h>
#include <QtGui/qimagewriter.h>
#include <QtGui/qinputmethod.h>
#include <QtGui/qkeysequence.h>
#include <QtGui/qmatrix.h>
//#include <QtGui/qmatrix4x4.h>
#include <QtGui/qmovie.h>
//#include <QtGui/qoffscreensurface.h>
//#include <QtGui/qopengl.h>
//#include <QtGui/qopenglbuffer.h>
//#include <QtGui/qopenglcontext.h>
//#include <QtGui/qopengldebug.h>
//#include <QtGui/qopengles2ext.h>
//#include <QtGui/qopenglext.h>
//#include <QtGui/qopenglextrafunctions.h>
//#include <QtGui/qopenglframebufferobject.h>
//#include <QtGui/qopenglfunctions.h>
//#include <QtGui/qopenglfunctions_1_0.h>
//#include <QtGui/qopenglfunctions_1_1.h>
//#include <QtGui/qopenglfunctions_1_2.h>
//#include <QtGui/qopenglfunctions_1_3.h>
//#include <QtGui/qopenglfunctions_1_4.h>
//#include <QtGui/qopenglfunctions_1_5.h>
//#include <QtGui/qopenglfunctions_2_0.h>
//#include <QtGui/qopenglfunctions_2_1.h>
//#include <QtGui/qopenglfunctions_3_0.h>
//#include <QtGui/qopenglfunctions_3_1.h>
//#include <QtGui/qopenglfunctions_3_2_compatibility.h>
//#include <QtGui/qopenglfunctions_3_2_core.h>
//#include <QtGui/qopenglfunctions_3_3_compatibility.h>
//#include <QtGui/qopenglfunctions_3_3_core.h>
//#include <QtGui/qopenglfunctions_4_0_compatibility.h>
//#include <QtGui/qopenglfunctions_4_0_core.h>
//#include <QtGui/qopenglfunctions_4_1_compatibility.h>
//#include <QtGui/qopenglfunctions_4_1_core.h>
//#include <QtGui/qopenglfunctions_4_2_compatibility.h>
//#include <QtGui/qopenglfunctions_4_2_core.h>
//#include <QtGui/qopenglfunctions_4_3_compatibility.h>
//#include <QtGui/qopenglfunctions_4_3_core.h>
//#include <QtGui/qopenglfunctions_4_4_compatibility.h>
//#include <QtGui/qopenglfunctions_4_4_core.h>
//#include <QtGui/qopenglfunctions_4_5_compatibility.h>
//#include <QtGui/qopenglfunctions_4_5_core.h>
//#include <QtGui/qopenglfunctions_es2.h>
//#include <QtGui/qopenglpaintdevice.h>
//#include <QtGui/qopenglpixeltransferoptions.h>
//#include <QtGui/qopenglshaderprogram.h>
//#include <QtGui/qopengltexture.h>
//#include <QtGui/qopengltextureblitter.h>
//#include <QtGui/qopengltimerquery.h>
//#include <QtGui/qopenglversionfunctions.h>
//#include <QtGui/qopenglvertexarrayobject.h>
//#include <QtGui/qopenglwindow.h>
#include <QtGui/qpagedpaintdevice.h>
#include <QtGui/qpagelayout.h>
#include <QtGui/qpagesize.h>
#include <QtGui/qpaintdevice.h>
//#include <QtGui/qpaintdevicewindow.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qpainter.h>
#include <QtGui/qpainterpath.h>
#include <QtGui/qpalette.h>
#include <QtGui/qpdfwriter.h>
#include <QtGui/qpen.h>
#include <QtGui/qpicture.h>
//#include <QtGui/qpictureformatplugin.h>
#include <QtGui/qpixelformat.h>
#include <QtGui/qpixmap.h>
//#include <QtGui/qpixmapcache.h>
#include <QtGui/qpolygon.h>
//#include <QtGui/qquaternion.h>
//#include <QtGui/qrasterwindow.h>
#include <QtGui/qrawfont.h>
#include <QtGui/qregion.h>
#include <QtGui/qrgb.h>
#include <QtGui/qrgba64.h>
#include <QtGui/qscreen.h>
//#include <QtGui/qsessionmanager.h>
#include <QtGui/qstandarditemmodel.h>
#include <QtGui/qstatictext.h>
#include <QtGui/qstylehints.h>
//#include <QtGui/qsurface.h>
//#include <QtGui/qsurfaceformat.h>
#include <QtGui/qsyntaxhighlighter.h>
//#include <QtGui/qtestsupport_gui.h>
#include <QtGui/qtextcursor.h>
#include <QtGui/qtextdocument.h>
#include <QtGui/qtextdocumentfragment.h>
#include <QtGui/qtextdocumentwriter.h>
#include <QtGui/qtextformat.h>
#include <QtGui/qtextlayout.h>
#include <QtGui/qtextlist.h>
#include <QtGui/qtextobject.h>
#include <QtGui/qtextoption.h>
#include <QtGui/qtexttable.h>
#include <QtGui/qtguiglobal.h>
//#include <QtGui/qtguiversion.h>
//#include <QtGui/qtgui-config.h>
#include <QtGui/qtouchdevice.h>
#include <QtGui/qtransform.h>
#include <QtGui/qvalidator.h>
#include <QtGui/qvector2d.h>
#include <QtGui/qvector3d.h>
#include <QtGui/qvector4d.h>
//#include <QtGui/qvulkanfunctions.h>
//#include <QtGui/qvulkaninstance.h>
//#include <QtGui/qvulkanwindow.h>
//#include <QtGui/qwindow.h>
#include <QtGui/qwindowdefs.h>
#include <QtGui/qwindowdefs_win.h>

// QtWidgets
#include <QtWidgets/qabstractbutton.h>
#include <QtWidgets/qabstractitemdelegate.h>
#include <QtWidgets/qabstractitemview.h>
#include <QtWidgets/qabstractscrollarea.h>
#include <QtWidgets/qabstractslider.h>
#include <QtWidgets/qabstractspinbox.h>
//#include <QtWidgets/qaccessiblewidget.h>
#include <QtWidgets/qaction.h>
#include <QtWidgets/qactiongroup.h>
#include <QtWidgets/qapplication.h>
#include <QtWidgets/qboxlayout.h>
#include <QtWidgets/qbuttongroup.h>
#include <QtWidgets/qcalendarwidget.h>
#include <QtWidgets/qcheckbox.h>
#include <QtWidgets/qcolordialog.h>
//#include <QtWidgets/qcolormap.h>
//#include <QtWidgets/qcolumnview.h>
#include <QtWidgets/qcombobox.h>
#include <QtWidgets/qcommandlinkbutton.h>
//#include <QtWidgets/qcommonstyle.h>
#include <QtWidgets/qcompleter.h>
//#include <QtWidgets/qdatawidgetmapper.h>
#include <QtWidgets/qdatetimeedit.h>
#include <QtWidgets/qdesktopwidget.h>
#include <QtWidgets/qdial.h>
#include <QtWidgets/qdialog.h>
#include <QtWidgets/qdialogbuttonbox.h>
#include <QtWidgets/qdirmodel.h>
#include <QtWidgets/qdockwidget.h>
//#include <QtWidgets/qdrawutil.h>
#include <QtWidgets/qerrormessage.h>
#include <QtWidgets/qfiledialog.h>
#include <QtWidgets/qfileiconprovider.h>
#include <QtWidgets/qfilesystemmodel.h>
//#include <QtWidgets/qfocusframe.h>
#include <QtWidgets/qfontcombobox.h>
#include <QtWidgets/qfontdialog.h>
#include <QtWidgets/qformlayout.h>
#include <QtWidgets/qframe.h>
#include <QtWidgets/qgesture.h>
#include <QtWidgets/qgesturerecognizer.h>
//#include <QtWidgets/qgraphicsanchorlayout.h>
//#include <QtWidgets/qgraphicseffect.h>
//#include <QtWidgets/qgraphicsgridlayout.h>
//#include <QtWidgets/qgraphicsitem.h>
//#include <QtWidgets/qgraphicsitemanimation.h>
//#include <QtWidgets/qgraphicslayout.h>
//#include <QtWidgets/qgraphicslayoutitem.h>
//#include <QtWidgets/qgraphicslinearlayout.h>
//#include <QtWidgets/qgraphicsproxywidget.h>
//#include <QtWidgets/qgraphicsscene.h>
//#include <QtWidgets/qgraphicssceneevent.h>
//#include <QtWidgets/qgraphicstransform.h>
//#include <QtWidgets/qgraphicsview.h>
//#include <QtWidgets/qgraphicswidget.h>
#include <QtWidgets/qgridlayout.h>
#include <QtWidgets/qgroupbox.h>
#include <QtWidgets/qheaderview.h>
#include <QtWidgets/qinputdialog.h>
//#include <QtWidgets/qitemdelegate.h>
//#include <QtWidgets/qitemeditorfactory.h>
//#include <QtWidgets/qkeyeventtransition.h>
#include <QtWidgets/qkeysequenceedit.h>
#include <QtWidgets/qlabel.h>
#include <QtWidgets/qlayout.h>
#include <QtWidgets/qlayoutitem.h>
#include <QtWidgets/qlcdnumber.h>
#include <QtWidgets/qlineedit.h>
#include <QtWidgets/qlistview.h>
#include <QtWidgets/qlistwidget.h>
//#include <QtWidgets/qmaccocoaviewcontainer_mac.h>
//#include <QtWidgets/qmacnativewidget_mac.h>
#include <QtWidgets/qmainwindow.h>
//#include <QtWidgets/qmdiarea.h>
//#include <QtWidgets/qmdisubwindow.h>
#include <QtWidgets/qmenu.h>
#include <QtWidgets/qmenubar.h>
#include <QtWidgets/qmessagebox.h>
//#include <QtWidgets/qmouseeventtransition.h>
//#include <QtWidgets/qopenglwidget.h>
#include <QtWidgets/qplaintextedit.h>
#include <QtWidgets/qprogressbar.h>
//#include <QtWidgets/qprogressdialog.h>
//#include <QtWidgets/qproxystyle.h>
#include <QtWidgets/qpushbutton.h>
#include <QtWidgets/qradiobutton.h>
#include <QtWidgets/qrubberband.h>
#include <QtWidgets/qscrollarea.h>
#include <QtWidgets/qscrollbar.h>
//#include <QtWidgets/qscroller.h>
//#include <QtWidgets/qscrollerproperties.h>
//#include <QtWidgets/qshortcut.h>
//#include <QtWidgets/qsizegrip.h>
#include <QtWidgets/qsizepolicy.h>
#include <QtWidgets/qslider.h>
#include <QtWidgets/qspinbox.h>
//#include <QtWidgets/qsplashscreen.h>
#include <QtWidgets/qsplitter.h>
//#include <QtWidgets/qstackedlayout.h>
#include <QtWidgets/qstackedwidget.h>
#include <QtWidgets/qstatusbar.h>
#include <QtWidgets/qstyle.h>
//#include <QtWidgets/qstyleditemdelegate.h>
//#include <QtWidgets/qstylefactory.h>
#include <QtWidgets/qstyleoption.h>
//#include <QtWidgets/qstylepainter.h>
//#include <QtWidgets/qstyleplugin.h>
//#include <QtWidgets/qsystemtrayicon.h>
#include <QtWidgets/qtabbar.h>
#include <QtWidgets/qtableview.h>
#include <QtWidgets/qtablewidget.h>
#include <QtWidgets/qtabwidget.h>
//#include <QtWidgets/qtestsupport_widgets.h>
#include <QtWidgets/qtextbrowser.h>
#include <QtWidgets/qtextedit.h>
#include <QtWidgets/qtoolbar.h>
#include <QtWidgets/qtoolbox.h>
#include <QtWidgets/qtoolbutton.h>
#include <QtWidgets/qtooltip.h>
#include <QtWidgets/qtreeview.h>
#include <QtWidgets/qtreewidget.h>
#include <QtWidgets/qtreewidgetitemiterator.h>
#include <QtWidgets/qtwidgetsglobal.h>
//#include <QtWidgets/qtwidgetsversion.h>
//#include <QtWidgets/qtwidgets-config.h>
//#include <QtWidgets/qundogroup.h>
//#include <QtWidgets/qundostack.h>
//#include <QtWidgets/qundoview.h>
//#include <QtWidgets/qwhatsthis.h>
#include <QtWidgets/qwidget.h>
//#include <QtWidgets/qwidgetaction.h>
//#include <QtWidgets/qwizard.h>

// QtNetwork
//#include <QtNetwork/qabstractnetworkcache.h>
#include <QtNetwork/qabstractsocket.h>
#include <QtNetwork/qauthenticator.h>
//#include <QtNetwork/qdnslookup.h>
//#include <QtNetwork/qdtls.h>
#include <QtNetwork/qhostaddress.h>
#include <QtNetwork/qhostinfo.h>
//#include <QtNetwork/qhstspolicy.h>
//#include <QtNetwork/qhttp2configuration.h>
//#include <QtNetwork/qhttpmultipart.h>
//#include <QtNetwork/qlocalserver.h>
//#include <QtNetwork/qlocalsocket.h>
#include <QtNetwork/qnetworkaccessmanager.h>
//#include <QtNetwork/qnetworkconfigmanager.h>
//#include <QtNetwork/qnetworkconfiguration.h>
#include <QtNetwork/qnetworkcookie.h>
#include <QtNetwork/qnetworkcookiejar.h>
//#include <QtNetwork/qnetworkdatagram.h>
//#include <QtNetwork/qnetworkdiskcache.h>
//#include <QtNetwork/qnetworkinterface.h>
#include <QtNetwork/qnetworkproxy.h>
//#include <QtNetwork/qnetworkreply.h>
#include <QtNetwork/qnetworkrequest.h>
//#include <QtNetwork/qnetworksession.h>
//#include <QtNetwork/qocspresponse.h>
//#include <QtNetwork/qpassworddigestor.h>
//#include <QtNetwork/qsctpserver.h>
//#include <QtNetwork/qsctpsocket.h>
#include <QtNetwork/qssl.h>
#include <QtNetwork/qsslcertificate.h>
#include <QtNetwork/qsslcertificateextension.h>
//#include <QtNetwork/qsslcipher.h>
#include <QtNetwork/qsslconfiguration.h>
//#include <QtNetwork/qssldiffiehellmanparameters.h>
//#include <QtNetwork/qsslellipticcurve.h>
#include <QtNetwork/qsslerror.h>
//#include <QtNetwork/qsslkey.h>
#include <QtNetwork/qsslpresharedkeyauthenticator.h>
#include <QtNetwork/qsslsocket.h>
//#include <QtNetwork/qtcpserver.h>
#include <QtNetwork/qtcpsocket.h>
#include <QtNetwork/qtnetworkglobal.h>
//#include <QtNetwork/qtnetworkversion.h>
//#include <QtNetwork/qtnetwork-config.h>
//#include <QtNetwork/qudpsocket.h>

// QtWebEngineCore
#include <QtWebEngineCore/qtwebenginecoreglobal.h>
//#include <QtWebEngineCore/qtwebenginecoreversion.h>
//#include <QtWebEngineCore/qtwebenginecore-config.h>
#include <QtWebEngineCore/qwebenginecallback.h>
#include <QtWebEngineCore/qwebengineclientcertificatestore.h>
#include <QtWebEngineCore/qwebenginecookiestore.h>
#include <QtWebEngineCore/qwebenginefindtextresult.h>
#include <QtWebEngineCore/qwebenginehttprequest.h>
#include <QtWebEngineCore/qwebenginenotification.h>
#include <QtWebEngineCore/qwebenginequotarequest.h>
#include <QtWebEngineCore/qwebengineregisterprotocolhandlerrequest.h>
#include <QtWebEngineCore/qwebengineurlrequestinfo.h>
#include <QtWebEngineCore/qwebengineurlrequestinterceptor.h>
#include <QtWebEngineCore/qwebengineurlrequestjob.h>
#include <QtWebEngineCore/qwebengineurlscheme.h>
#include <QtWebEngineCore/qwebengineurlschemehandler.h>

// QtWebEngineWidgets
#include <QtWebEngineWidgets/qtwebenginewidgetsglobal.h>
//#include <QtWebEngineWidgets/qtwebenginewidgetsversion.h>
//#include <QtWebEngineWidgets/qtwebenginewidgets-config.h>
#include <QtWebEngineWidgets/qwebenginecertificateerror.h>
#include <QtWebEngineWidgets/qwebengineclientcertificateselection.h>
#include <QtWebEngineWidgets/qwebenginecontextmenudata.h>
#include <QtWebEngineWidgets/qwebenginedownloaditem.h>
#include <QtWebEngineWidgets/qwebenginefullscreenrequest.h>
#include <QtWebEngineWidgets/qwebenginehistory.h>
#include <QtWebEngineWidgets/qwebenginepage.h>
#include <QtWebEngineWidgets/qwebengineprofile.h>
#include <QtWebEngineWidgets/qwebenginescript.h>
#include <QtWebEngineWidgets/qwebenginescriptcollection.h>
#include <QtWebEngineWidgets/qwebenginesettings.h>
#include <QtWebEngineWidgets/qwebengineview.h>
